### ISSUE TITLE
Keep getting this bug and have to Drop DB and rebuild fixtures

### ISSUE THREAD

**Issue by glassresistor** [codeforamerica/intake#1066]
This error keeps happening and it throws me off for about an hour.  Dropping the database and rebuilding the fixtures fixes tests but its causing confusion and lost time.

I can't figure out exactly what is triggering the issue but its related to the way we are temporary hack we are doing with new_fixtures.  This is a reason to spend some time removing it since its causing issues developing.

```sh
make test
./manage.py test clips user_accounts intake formation health_check phone partnerships \
	--verbosity 2
Creating test database for alias 'purged' ('test_intake')...
Got an error creating the test database: database "test_intake" already exists

Type 'yes' if you would like to try deleting the test database 'test_intake', or 'no' to cancel: yes
Destroying old test database for alias 'purged' ('test_intake')...
Operations to perform:
  Synchronize unmigrated apps: allauth, behave_django, compressor, debug_toolbar, django_extensions, django_jinja, favicons, formation, health_check, heroku_hijack_collectstatic, messages, phone, rest_framework, staticfiles, storages, url_robots
  Apply all migrations: account, admin, auth, clips, contenttypes, intake, invitations, partnerships, sessions, sites, socialaccount, taggit, user_accounts
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying account.0001_initial... OK
  Applying account.0002_email_max_length... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying clips.0001_initial... OK
  Applying clips.0002_clip_title... OK
  Applying user_accounts.0001_initial... OK
  Applying invitations.0001_initial... OK
  Applying invitations.0002_auto_20151126_0426... OK
  Applying invitations.0003_auto_20151126_1523... OK
  Applying user_accounts.0002_auto_20160524_1808... OK
  Applying user_accounts.0003_auto_20160525_1728... OK
  Applying user_accounts.0004_userprofile_should_get_notifications... OK
  Applying user_accounts.0005_organization_is_receiving_agency... OK
  Applying intake.0001_initial... OK
  Applying intake.0002_fillablepdf... OK
  Applying intake.0003_fillablepdf_name... OK
  Applying intake.0004_auto_20160603_2355... OK
  Applying intake.0005_auto_20160606_1949... OK
  Applying intake.0006_auto_20160614_2216... OK
  Applying intake.0007_auto_20160615_1954... OK
  Applying intake.0008_auto_20160615_2307... OK
  Applying intake.0009_auto_20160615_2323... OK
  Applying intake.0010_auto_20160706_2000... OK
  Applying intake.0011_confirmationsentlogentry_message_sent... OK
  Applying intake.0012_auto_20160706_2010... OK
  Applying intake.0013_add_county_model... OK
  Applying user_accounts.0006_add_county_model... OK
  Applying intake.0014_county_name... OK
  Applying intake.0015_add_default_counties... OK
  Applying user_accounts.0007_add_default_orgs_for_counties...Traceback (most recent call last):
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.IntegrityError: null value in column "address" violates not-null constraint
DETAIL:  Failing row contains (19, Code for America, , , f, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 8, in <module>
    execute_from_command_line(sys.argv)
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/core/management/commands/test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/core/management/commands/test.py", line 72, in handle
    failures = test_runner.run_tests(test_labels)
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/test/runner.py", line 549, in run_tests
    old_config = self.setup_databases()
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/test/runner.py", line 499, in setup_databases
    self.parallel, **kwargs
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/test/runner.py", line 743, in setup_databases
    serialize=connection.settings_dict.get("TEST", {}).get("SERIALIZE", True),
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/db/backends/base/creation.py", line 70, in create_test_db
    run_syncdb=True,
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/core/management/__init__.py", line 130, in call_command
    return command.execute(*args, **defaults)
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/db/migrations/operations/special.py", line 189, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/home/mikela/code/intake/project/migration_utils.py", line 98, in forward
    cls.load_fixture(spec, *args)
  File "/home/mikela/code/intake/project/migration_utils.py", line 86, in load_fixture
    cls.update_or_create_object(obj, queryset)
  File "/home/mikela/code/intake/project/migration_utils.py", line 71, in update_or_create_object
    instance.save()
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/core/serializers/base.py", line 201, in save
    models.Model.save_base(self.object, using=using, raw=True, **kwargs)
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/db/models/base.py", line 824, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/db/models/base.py", line 908, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/db/models/base.py", line 947, in _do_insert
    using=using, raw=raw)
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/db/models/query.py", line 1045, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1054, in execute_sql
    cursor.execute(sql, params)
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "address" violates not-null constraint
DETAIL:  Failing row contains (19, Code for America, , , f, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null).

Makefile:14: recipe for target 'test' failed
make: *** [test] Error 1
```

**Comment by bengolder** [comment]
What are your database settings, in `local_settings.py`?

This line stood out to me:
```
Creating test database for alias 'purged'
```
typically, the alias would be `default`

The other thing I notice about this stack trace is that it's failing on an old data migration, while trying to load default organizations.

**Comment by glassresistor** [comment]
Creating test database for alias 'purged' is normal and unrelated, purged is the new database I've add.  I was getting this error on the develop branch before those changes we merged in.

My suggestion is to rather than spend time trying to figure exactly waht about new_fixtures is breaking and fixing the database, we just go ahead and remove the need to generate these fixtures with new fixtures like we had already planned.  This should fix the problem and cleans up our development process.

**Comment by glassresistor** [comment]
So travis got this bug now as well.  The exact same code failed once then worked when I forced a rebuild
Failing
https://travis-ci.org/codeforamerica/intake/builds/265732899
Working(but same code)
https://travis-ci.org/codeforamerica/intake/builds/265734157

This also happed on the develop branch at the same time and worked when I forced a reboot.

**Comment by glassresistor** [comment]
This is now happening on Travis CI as well on develop

**Comment by glassresistor** [comment]
django.db.utils.IntegrityError: null value in column "address" violates not-null constraint
DETAIL:  Failing row contains (19, Code for America, , , f, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null).

Its complaining that address can't be null and looking at the json file the address is null, so that makes sense.  

This the state of the db after it fails.  Notice that the table does not have a address column.
```
\d user_accounts_organization
                                       Table "public.user_accounts_organization"
       Column        |          Type          |                                Modifiers                                
---------------------+------------------------+-------------------------------------------------------------------------
 id                  | integer                | not null default nextval('user_accounts_organization_id_seq'::regclass)
 name                | character varying(50)  | not null
 website             | character varying(200) | not null
 blurb               | text                   | not null
 is_receiving_agency | boolean                | not null
 county_id           | integer                | 
Indexes:
    "user_accounts_organization_pkey" PRIMARY KEY, btree (id)
    "user_accounts_organization_name_24754af7_uniq" UNIQUE CONSTRAINT, btree (name)
    "user_accounts_organization_d19428be" btree (county_id)
    "user_accounts_organization_name_24754af7_like" btree (name varchar_pattern_ops)
Foreign-key constraints:
    "user_accounts_organizati_county_id_1eca7920_fk_intake_county_id" FOREIGN KEY (county_id) REFERENCES intake_county(id) DEFERRABLE INITIALLY DEFERRED
Referenced by:
    TABLE "user_accounts_invitation" CONSTRAINT "user__organization_id_4de6e29f_fk_user_accounts_organization_id" FOREIGN KEY (organization_id) REFERENCES user_accounts_organization(id) DEFERRABLE INITIALLY DEFERRED
    TABLE "user_accounts_userprofile" CONSTRAINT "user__organization_id_fa919f49_fk_user_accounts_organization_id" FOREIGN KEY (organization_id) REFERENCES user_accounts_organization(id) DEFERRABLE INITIALLY DEFERRED
```

**Comment by glassresistor** [comment]
So I went into django and printed the connection off throughout a failing migrations and it is using the normal database and not the test one to try and insert.

I also have some evidence this is happening for counties as well but it isn't trigger the an db error.  But sometimes this test will pass but then fail because they are no counties in the database either.  So bottom example.

So the reason it keeps failing after a bad migration even though it still connects to the correct database  1/2 the time but then doesn't have counties.  While using PDB it would always pass and I couldn't figure out why but adding a pause solves the problem so I'm thinking its a race condition.

```
make test.everything 
pep8
make test.coverage.keepdb
make[1]: Entering directory '/home/mikela/code/intake'
coverage run \
	./manage.py test clips user_accounts intake formation health_check phone partnerships \
	--verbosity 2 --keepdb
Using existing test database for alias 'pruned' ('test_intake')...
<connection object at 0x7f0c7c1d46a8; dsn: 'dbname=test_intake user=mikela', closed: 0>
<connection object at 0x7f0c7c1d46a8; dsn: 'dbname=test_intake user=mikela', closed: 0>
Operations to perform:
  Synchronize unmigrated apps: allauth, behave_django, compressor, debug_toolbar, django_extensions, django_jinja, favicons, formation, health_check, heroku_hijack_collectstatic, messages, phone, rest_framework, staticfiles, storages, url_robots
  Apply all migrations: account, admin, auth, clips, contenttypes, intake, invitations, partnerships, sessions, sites, socialaccount, taggit, user_accounts
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
Running migrations:
  Applying user_accounts.0007_add_default_orgs_for_counties...<connection object at 0x7f0c7c1d46a8; dsn: 'dbname=test_intake user=mikela', closed: 0>
<connection object at 0x7f0c7c1d49d8; dsn: 'dbname=intake user=mikela', closed: 0>
Traceback (most recent call last):
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/db/backends/utils.py", line 67, in execute
    return self.cursor.execute(sql, params)
psycopg2.IntegrityError: null value in column "address" violates not-null constraint
DETAIL:  Failing row contains (36, Code for America, , , f, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 8, in <module>
    execute_from_command_line(sys.argv)
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/core/management/commands/test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/core/management/commands/test.py", line 72, in handle
    failures = test_runner.run_tests(test_labels)
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/test/runner.py", line 549, in run_tests
    old_config = self.setup_databases()
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/test/runner.py", line 499, in setup_databases
    self.parallel, **kwargs
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/test/runner.py", line 743, in setup_databases
    serialize=connection.settings_dict.get("TEST", {}).get("SERIALIZE", True),
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/db/backends/base/creation.py", line 70, in create_test_db
    run_syncdb=True,
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/core/management/__init__.py", line 130, in call_command
    return command.execute(*args, **defaults)
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/db/migrations/operations/special.py", line 189, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/home/mikela/code/intake/project/migration_utils.py", line 98, in forward
    cls.load_fixture(spec, *args)
  File "/home/mikela/code/intake/project/migration_utils.py", line 86, in load_fixture
    cls.update_or_create_object(obj, queryset)
  File "/home/mikela/code/intake/project/migration_utils.py", line 71, in update_or_create_object
    instance.save()
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/core/serializers/base.py", line 201, in save
    models.Model.save_base(self.object, using=using, raw=True, **kwargs)
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/db/models/base.py", line 824, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/db/models/base.py", line 908, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/db/models/base.py", line 947, in _do_insert
    using=using, raw=raw)
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/db/models/query.py", line 1045, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1054, in execute_sql
    cursor.execute(sql, params)
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/db/backends/utils.py", line 67, in execute
    return self.cursor.execute(sql, params)
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/mikela/.conda/envs/intake/lib/python3.5/site-packages/django/db/backends/utils.py", line 67, in execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "address" violates not-null constraint
DETAIL:  Failing row contains (36, Code for America, , , f, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null).

Makefile:46: recipe for target 'test.coverage.keepdb' failed
make[1]: *** [test.coverage.keepdb] Error 1
make[1]: Leaving directory '/home/mikela/code/intake'
Makefile:58: recipe for target 'test.everything' failed
make: *** [test.everything] Error 2
```


This is connecting to the proper database but then failing because counties were added to my real database.

**Comment by glassresistor** [comment]
So I rewrote intake/0015_add_default_counties to use bulk_create and simplify our code.  I was still getting the same error.  I did some digging and found this error.

https://code.djangoproject.com/ticket/14415

"Solved" this by removing the 2nd database.  We should see if Django 1.11 fixes this bug.
