### ISSUE TITLE
Odd Error in Tests

### ISSUE THREAD

**Issue by glassresistor** [codeforamerica/intake#1360]
We've been getting these errors in tests for a while. Any idea what this is or where it came from?  cc: @bengolder 
```
easy audit had an m2m-changed exception.
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 170, in __get__
    rel_obj = getattr(instance, self.cache_name)
AttributeError: 'StatusUpdate' object has no attribute '_status_type_cache'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/src/django-easy-audit/easyaudit/signals.py", line 141, in m2m_changed
    object_repr=str(instance),
  File "/home/travis/build/codeforamerica/intake/intake/models/status_update.py", line 31, in __str__
    self.status_type.display_name,
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 179, in __get__
    rel_obj = qs.get()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/db/models/query.py", line 385, in get
    self.model._meta.object_name
intake.models.status_type.DoesNotExist: StatusType matching query does not exist.
easy audit had an m2m-changed exception.
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 170, in __get__
    rel_obj = getattr(instance, self.cache_name)
AttributeError: 'StatusUpdate' object has no attribute '_status_type_cache'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/src/django-easy-audit/easyaudit/signals.py", line 141, in m2m_changed
    object_repr=str(instance),
  File "/home/travis/build/codeforamerica/intake/intake/models/status_update.py", line 31, in __str__
    self.status_type.display_name,
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 179, in __get__
    rel_obj = qs.get()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/db/models/query.py", line 385, in get
    self.model._meta.object_name
intake.models.status_type.DoesNotExist: StatusType matching query does not exist.

```

**Comment by bengolder** [comment]
I'm not sure. But my best guess is that something is acting on a `StatusUpdate` instance that does not have an associated `StatusType` (it always should have one), and easy audit is choking when trying to call `__str__` on that `StatusUpdate` instance, which would normally include the `display_name` of the associated `status_type`.

I'm surprised by this error message though:
```
AttributeError: 'StatusUpdate' object has no attribute '_status_type_cache'
```
I would expect a missing `status_update` to trigger a different error

**Comment by glassresistor** [comment]
Yeah this error looks like it been around for a pretty long time now though. Maybe since easyaudit was added.  Its not causing failures but it means its pretty hard to understand whats happening.

**Comment by glassresistor** [comment]
The warning happen on almost all test instances though
